apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-27T10:23:22Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: test-secret
